name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build Core
        run: dotnet build --configuration Release --no-restore PictSharp.Core /p:PackageVersion=1.0.$GITHUB_RUN_ID
      - name: Build ImageSharp
        run: dotnet build --configuration Release --no-restore PictSharp.ImageSharpAdaptor /p:PackageVersion=1.0.$GITHUB_RUN_ID
      - name: Test
        run: dotnet test --no-restore --verbosity normal PictSharp.Tests
      - name: Package Core
        run: dotnet pack --configuration Release PictSharp.Core /p:PackageVersion=1.0.$GITHUB_RUN_ID
      - name: Package ImageSharpAdaptor
        run: dotnet pack --configuration Release PictSharp.ImageSharpAdaptor /p:PackageVersion=1.0.$GITHUB_RUN_ID
      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
