name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build Core
        run: dotnet build --configuration Release --no-restore PictSharp.Core
      - name: Build ImageSharp
        run: dotnet build --configuration Release --no-restore PictSharp.ImageSharpAdaptor
      - name: Test
        run: dotnet test --no-restore --verbosity normal PictSharp.Tests
